from enum import StrEnum


class TaskState(StrEnum):
    DRAFT = "DRAFT"
    NEEDS_CONTEXT = "NEEDS_CONTEXT"
    READY_FOR_ANALYSIS = "READY_FOR_ANALYSIS"
    ANALYZING = "ANALYZING"
    BLOCKED = "BLOCKED"
    READY_FOR_IMPLEMENTATION = "READY_FOR_IMPLEMENTATION"
    IMPLEMENTING = "IMPLEMENTING"
    READY_FOR_REVIEW = "READY_FOR_REVIEW"
    CHANGES_REQUESTED = "CHANGES_REQUESTED"
    READY_FOR_ARCHITECT_APPROVAL = "READY_FOR_ARCHITECT_APPROVAL"
    APPROVED_FOR_PREPRODUCTION = "APPROVED_FOR_PREPRODUCTION"
    VALIDATING_PREPRODUCTION = "VALIDATING_PREPRODUCTION"
    PREPRODUCTION_FAILED = "PREPRODUCTION_FAILED"
    READY_FOR_PRODUCTION = "READY_FOR_PRODUCTION"
    PRODUCTION_APPROVED = "PRODUCTION_APPROVED"
    DEPLOYING = "DEPLOYING"
    OBSERVING = "OBSERVING"
    COMPLETED = "COMPLETED"
    ROLLED_BACK = "ROLLED_BACK"
    CANCELLED = "CANCELLED"


class ActorKind(StrEnum):
    HUMAN = "HUMAN"
    AGENT = "AGENT"
    SERVICE = "SERVICE"
    TEAM = "TEAM"
    EXTERNAL_SYSTEM = "EXTERNAL_SYSTEM"


class RequirementType(StrEnum):
    FUNCTIONAL = "FUNCTIONAL"
    NON_FUNCTIONAL = "NON_FUNCTIONAL"
    ARCHITECTURE = "ARCHITECTURE"
    SECURITY = "SECURITY"
    DATA = "DATA"
    OPERATIONAL = "OPERATIONAL"
    DEPLOYMENT = "DEPLOYMENT"
    COMPATIBILITY = "COMPATIBILITY"
    OBSERVABILITY = "OBSERVABILITY"


class ContextAuthority(StrEnum):
    AUTHORITATIVE = "AUTHORITATIVE"
    APPROVED = "APPROVED"
    PROPOSED = "PROPOSED"
    INFERRED = "INFERRED"
    UNVERIFIED = "UNVERIFIED"


class ContextStatus(StrEnum):
    ACTIVE = "ACTIVE"
    SUPERSEDED = "SUPERSEDED"
    DEPRECATED = "DEPRECATED"


class EpicContextKind(StrEnum):
    BUSINESS = "BUSINESS"
    ARCHITECTURE = "ARCHITECTURE"
    DOMAIN = "DOMAIN"
    CODEBASE = "CODEBASE"
    CONSTRAINT = "CONSTRAINT"
    SECURITY = "SECURITY"
    ENVIRONMENT = "ENVIRONMENT"
    OPERATIONS = "OPERATIONS"
    TESTING = "TESTING"
    DEPLOYMENT = "DEPLOYMENT"
    LESSON_LEARNED = "LESSON_LEARNED"
    DECISION_SUMMARY = "DECISION_SUMMARY"
    OTHER = "OTHER"


class EpicContextStatus(StrEnum):
    ACTIVE = "ACTIVE"
    SUPERSEDED = "SUPERSEDED"
    DEPRECATED = "DEPRECATED"
    REJECTED = "REJECTED"


class EvidenceKind(StrEnum):
    IMPLEMENTATION = "IMPLEMENTATION"
    PREPRODUCTION_VALIDATION = "PREPRODUCTION_VALIDATION"
    PRODUCTION_DEPLOYMENT = "PRODUCTION_DEPLOYMENT"
    OBSERVATION = "OBSERVATION"


class ReviewStatus(StrEnum):
    PENDING = "PENDING"
    APPROVED = "APPROVED"
    CHANGES_REQUESTED = "CHANGES_REQUESTED"


class Severity(StrEnum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"
