"""initial_domain_schema

Revision ID: 32d7bbfd4d03
Revises:
Create Date: 2026-07-11 21:27:54.938197
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "32d7bbfd4d03"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "actors",
        sa.Column(
            "kind",
            sa.Enum("HUMAN", "AGENT", "SERVICE", "TEAM", "EXTERNAL_SYSTEM", name="actor_kind"),
            nullable=False,
        ),
        sa.Column("display_name", sa.String(length=250), nullable=False),
        sa.Column("external_ref", sa.String(length=500), nullable=True),
        sa.Column("metadata", sa.JSON(), server_default="{}", nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("external_ref"),
    )
    op.create_table(
        "domain_events",
        sa.Column("aggregate_type", sa.String(length=100), nullable=False),
        sa.Column("aggregate_id", sa.UUID(), nullable=False),
        sa.Column("aggregate_sequence", sa.Integer(), nullable=False),
        sa.Column("event_type", sa.String(length=150), nullable=False),
        sa.Column("actor_id", sa.UUID(), nullable=True),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("correlation_id", sa.UUID(), nullable=True),
        sa.Column("causation_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.CheckConstraint("aggregate_sequence > 0", name="ck_event_sequence_positive"),
        sa.ForeignKeyConstraint(["actor_id"], ["actors.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "aggregate_type",
            "aggregate_id",
            "aggregate_sequence",
            name="uq_event_aggregate_sequence",
        ),
    )
    op.create_index(
        "ix_domain_event_timeline",
        "domain_events",
        ["aggregate_id", "occurred_at", "id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_domain_events_aggregate_id"), "domain_events", ["aggregate_id"], unique=False
    )
    op.create_table(
        "epics",
        sa.Column("title", sa.String(length=250), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("problem_statement", sa.Text(), nullable=False),
        sa.Column("desired_outcome", sa.Text(), nullable=False),
        sa.Column("architect_actor_id", sa.UUID(), nullable=False),
        sa.Column("created_by_actor_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.ForeignKeyConstraint(["architect_actor_id"], ["actors.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["created_by_actor_id"], ["actors.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "tasks",
        sa.Column("epic_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=250), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("objective", sa.Text(), nullable=False),
        sa.Column(
            "state",
            sa.Enum(
                "DRAFT",
                "NEEDS_CONTEXT",
                "READY_FOR_ANALYSIS",
                "ANALYZING",
                "BLOCKED",
                "READY_FOR_IMPLEMENTATION",
                "IMPLEMENTING",
                "READY_FOR_REVIEW",
                "CHANGES_REQUESTED",
                "READY_FOR_ARCHITECT_APPROVAL",
                "APPROVED_FOR_PREPRODUCTION",
                "VALIDATING_PREPRODUCTION",
                "PREPRODUCTION_FAILED",
                "READY_FOR_PRODUCTION",
                "PRODUCTION_APPROVED",
                "DEPLOYING",
                "OBSERVING",
                "COMPLETED",
                "ROLLED_BACK",
                "CANCELLED",
                name="task_state",
            ),
            nullable=False,
        ),
        sa.Column(
            "blocked_from_state",
            sa.Enum(
                "DRAFT",
                "NEEDS_CONTEXT",
                "READY_FOR_ANALYSIS",
                "ANALYZING",
                "BLOCKED",
                "READY_FOR_IMPLEMENTATION",
                "IMPLEMENTING",
                "READY_FOR_REVIEW",
                "CHANGES_REQUESTED",
                "READY_FOR_ARCHITECT_APPROVAL",
                "APPROVED_FOR_PREPRODUCTION",
                "VALIDATING_PREPRODUCTION",
                "PREPRODUCTION_FAILED",
                "READY_FOR_PRODUCTION",
                "PRODUCTION_APPROVED",
                "DEPLOYING",
                "OBSERVING",
                "COMPLETED",
                "ROLLED_BACK",
                "CANCELLED",
                name="task_state",
            ),
            nullable=True,
        ),
        sa.Column("architect_actor_id", sa.UUID(), nullable=False),
        sa.Column("created_by_actor_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.CheckConstraint(
            "state = 'BLOCKED' OR blocked_from_state IS NULL", name="ck_task_blocked_from"
        ),
        sa.ForeignKeyConstraint(["architect_actor_id"], ["actors.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["created_by_actor_id"], ["actors.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["epic_id"], ["epics.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_tasks_epic_id"), "tasks", ["epic_id"], unique=False)
    op.create_table(
        "acceptance_criteria",
        sa.Column("task_id", sa.UUID(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("verification_method", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("created_by_actor_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.ForeignKeyConstraint(["created_by_actor_id"], ["actors.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["task_id"], ["tasks.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_acceptance_criteria_task_id"), "acceptance_criteria", ["task_id"], unique=False
    )
    op.create_table(
        "blockers",
        sa.Column("task_id", sa.UUID(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("created_by_actor_id", sa.UUID(), nullable=False),
        sa.Column("resolved_by_actor_id", sa.UUID(), nullable=True),
        sa.Column("resolution", sa.Text(), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.CheckConstraint(
            "status = 'OPEN' OR (resolution IS NOT NULL "
            "AND resolved_by_actor_id IS NOT NULL AND resolved_at IS NOT NULL)",
            name="ck_blocker_resolution",
        ),
        sa.CheckConstraint("status IN ('OPEN','RESOLVED')", name="ck_blocker_status"),
        sa.ForeignKeyConstraint(["created_by_actor_id"], ["actors.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["resolved_by_actor_id"], ["actors.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["task_id"], ["tasks.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_blockers_task_id"), "blockers", ["task_id"], unique=False)
    op.create_table(
        "context_entries",
        sa.Column("task_id", sa.UUID(), nullable=False),
        sa.Column("kind", sa.String(length=50), nullable=False),
        sa.Column("title", sa.String(length=250), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("source_uri", sa.String(length=2000), nullable=True),
        sa.Column(
            "authority",
            sa.Enum(
                "AUTHORITATIVE",
                "APPROVED",
                "PROPOSED",
                "INFERRED",
                "UNVERIFIED",
                name="context_authority",
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "SUPERSEDED", "DEPRECATED", name="context_status"),
            nullable=False,
        ),
        sa.Column("supersedes_context_entry_id", sa.UUID(), nullable=True),
        sa.Column("created_by_actor_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.CheckConstraint(
            "supersedes_context_entry_id IS NULL OR supersedes_context_entry_id <> id",
            name="ck_context_not_self",
        ),
        sa.ForeignKeyConstraint(["created_by_actor_id"], ["actors.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["supersedes_context_entry_id"], ["context_entries.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["task_id"], ["tasks.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_context_entries_task_id"), "context_entries", ["task_id"], unique=False
    )
    op.create_table(
        "decisions",
        sa.Column("task_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=250), nullable=False),
        sa.Column("proposal", sa.Text(), nullable=False),
        sa.Column("rationale", sa.Text(), nullable=False),
        sa.Column("is_required", sa.Boolean(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("proposed_by_actor_id", sa.UUID(), nullable=False),
        sa.Column("approved_by_actor_id", sa.UUID(), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("supersedes_decision_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.CheckConstraint(
            "status IN ('PROPOSED','APPROVED','REJECTED','SUPERSEDED')", name="ck_decision_status"
        ),
        sa.ForeignKeyConstraint(["approved_by_actor_id"], ["actors.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["proposed_by_actor_id"], ["actors.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["supersedes_decision_id"], ["decisions.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["task_id"], ["tasks.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_decisions_task_id"), "decisions", ["task_id"], unique=False)
    op.create_table(
        "implementation_runs",
        sa.Column("task_id", sa.UUID(), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("reference_uri", sa.String(length=2000), nullable=True),
        sa.Column("registered_by_actor_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.ForeignKeyConstraint(["registered_by_actor_id"], ["actors.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["task_id"], ["tasks.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_implementation_runs_task_id"), "implementation_runs", ["task_id"], unique=False
    )
    op.create_table(
        "questions",
        sa.Column("task_id", sa.UUID(), nullable=False),
        sa.Column("question", sa.Text(), nullable=False),
        sa.Column("is_blocking", sa.Boolean(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("impact_if_unanswered", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("asked_by_actor_id", sa.UUID(), nullable=False),
        sa.Column("assigned_to_actor_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.CheckConstraint("status IN ('OPEN','ANSWERED','WITHDRAWN')", name="ck_question_status"),
        sa.ForeignKeyConstraint(["asked_by_actor_id"], ["actors.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["assigned_to_actor_id"], ["actors.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["task_id"], ["tasks.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_questions_task_id"), "questions", ["task_id"], unique=False)
    op.create_table(
        "requirements",
        sa.Column("task_id", sa.UUID(), nullable=False),
        sa.Column(
            "requirement_type",
            sa.Enum(
                "FUNCTIONAL",
                "NON_FUNCTIONAL",
                "ARCHITECTURE",
                "SECURITY",
                "DATA",
                "OPERATIONAL",
                "DEPLOYMENT",
                "COMPATIBILITY",
                "OBSERVABILITY",
                name="requirement_type",
            ),
            nullable=False,
        ),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("created_by_actor_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.CheckConstraint(
            "status IN ('PROPOSED','CONFIRMED','WITHDRAWN')", name="ck_requirement_status"
        ),
        sa.ForeignKeyConstraint(["created_by_actor_id"], ["actors.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["task_id"], ["tasks.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_requirements_task_id"), "requirements", ["task_id"], unique=False)
    op.create_table(
        "reviews",
        sa.Column("task_id", sa.UUID(), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("PENDING", "APPROVED", "CHANGES_REQUESTED", name="review_status"),
            nullable=False,
        ),
        sa.Column("reviewer_actor_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.ForeignKeyConstraint(["reviewer_actor_id"], ["actors.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["task_id"], ["tasks.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_reviews_task_id"), "reviews", ["task_id"], unique=False)
    op.create_table(
        "task_actors",
        sa.Column("task_id", sa.UUID(), nullable=False),
        sa.Column("actor_id", sa.UUID(), nullable=False),
        sa.Column("role", sa.String(length=100), nullable=False),
        sa.Column("added_by_actor_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["actor_id"], ["actors.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["added_by_actor_id"], ["actors.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["task_id"], ["tasks.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("task_id", "actor_id"),
    )
    op.create_table(
        "task_state_transitions",
        sa.Column("task_id", sa.UUID(), nullable=False),
        sa.Column(
            "from_state",
            sa.Enum(
                "DRAFT",
                "NEEDS_CONTEXT",
                "READY_FOR_ANALYSIS",
                "ANALYZING",
                "BLOCKED",
                "READY_FOR_IMPLEMENTATION",
                "IMPLEMENTING",
                "READY_FOR_REVIEW",
                "CHANGES_REQUESTED",
                "READY_FOR_ARCHITECT_APPROVAL",
                "APPROVED_FOR_PREPRODUCTION",
                "VALIDATING_PREPRODUCTION",
                "PREPRODUCTION_FAILED",
                "READY_FOR_PRODUCTION",
                "PRODUCTION_APPROVED",
                "DEPLOYING",
                "OBSERVING",
                "COMPLETED",
                "ROLLED_BACK",
                "CANCELLED",
                name="task_state",
            ),
            nullable=False,
        ),
        sa.Column(
            "to_state",
            sa.Enum(
                "DRAFT",
                "NEEDS_CONTEXT",
                "READY_FOR_ANALYSIS",
                "ANALYZING",
                "BLOCKED",
                "READY_FOR_IMPLEMENTATION",
                "IMPLEMENTING",
                "READY_FOR_REVIEW",
                "CHANGES_REQUESTED",
                "READY_FOR_ARCHITECT_APPROVAL",
                "APPROVED_FOR_PREPRODUCTION",
                "VALIDATING_PREPRODUCTION",
                "PREPRODUCTION_FAILED",
                "READY_FOR_PRODUCTION",
                "PRODUCTION_APPROVED",
                "DEPLOYING",
                "OBSERVING",
                "COMPLETED",
                "ROLLED_BACK",
                "CANCELLED",
                name="task_state",
            ),
            nullable=False,
        ),
        sa.Column("requested_by_actor_id", sa.UUID(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("task_version", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["requested_by_actor_id"], ["actors.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["task_id"], ["tasks.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_task_state_transitions_task_id"),
        "task_state_transitions",
        ["task_id"],
        unique=False,
    )
    op.create_table(
        "evidence",
        sa.Column("task_id", sa.UUID(), nullable=False),
        sa.Column("implementation_run_id", sa.UUID(), nullable=True),
        sa.Column(
            "kind",
            sa.Enum(
                "IMPLEMENTATION",
                "PREPRODUCTION_VALIDATION",
                "PRODUCTION_DEPLOYMENT",
                "OBSERVATION",
                name="evidence_kind",
            ),
            nullable=False,
        ),
        sa.Column("title", sa.String(length=250), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("reference_uri", sa.String(length=2000), nullable=True),
        sa.Column("passed", sa.Boolean(), nullable=True),
        sa.Column("registered_by_actor_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.ForeignKeyConstraint(
            ["implementation_run_id"], ["implementation_runs.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["registered_by_actor_id"], ["actors.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["task_id"], ["tasks.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_evidence_task_id"), "evidence", ["task_id"], unique=False)
    op.create_table(
        "question_answers",
        sa.Column("question_id", sa.UUID(), nullable=False),
        sa.Column("answer", sa.Text(), nullable=False),
        sa.Column("answered_by_actor_id", sa.UUID(), nullable=False),
        sa.Column("supersedes_answer_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["answered_by_actor_id"], ["actors.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["question_id"], ["questions.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["supersedes_answer_id"], ["question_answers.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_question_answers_question_id"), "question_answers", ["question_id"], unique=False
    )
    op.create_table(
        "review_findings",
        sa.Column("review_id", sa.UUID(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column(
            "severity",
            sa.Enum("LOW", "MEDIUM", "HIGH", "CRITICAL", name="severity"),
            nullable=False,
        ),
        sa.Column("is_blocking", sa.Boolean(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("resolution", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.CheckConstraint("status IN ('OPEN','RESOLVED')", name="ck_review_finding_status"),
        sa.ForeignKeyConstraint(["review_id"], ["reviews.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_review_findings_review_id"), "review_findings", ["review_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_review_findings_review_id"), table_name="review_findings")
    op.drop_table("review_findings")
    op.drop_index(op.f("ix_question_answers_question_id"), table_name="question_answers")
    op.drop_table("question_answers")
    op.drop_index(op.f("ix_evidence_task_id"), table_name="evidence")
    op.drop_table("evidence")
    op.drop_index(op.f("ix_task_state_transitions_task_id"), table_name="task_state_transitions")
    op.drop_table("task_state_transitions")
    op.drop_table("task_actors")
    op.drop_index(op.f("ix_reviews_task_id"), table_name="reviews")
    op.drop_table("reviews")
    op.drop_index(op.f("ix_requirements_task_id"), table_name="requirements")
    op.drop_table("requirements")
    op.drop_index(op.f("ix_questions_task_id"), table_name="questions")
    op.drop_table("questions")
    op.drop_index(op.f("ix_implementation_runs_task_id"), table_name="implementation_runs")
    op.drop_table("implementation_runs")
    op.drop_index(op.f("ix_decisions_task_id"), table_name="decisions")
    op.drop_table("decisions")
    op.drop_index(op.f("ix_context_entries_task_id"), table_name="context_entries")
    op.drop_table("context_entries")
    op.drop_index(op.f("ix_blockers_task_id"), table_name="blockers")
    op.drop_table("blockers")
    op.drop_index(op.f("ix_acceptance_criteria_task_id"), table_name="acceptance_criteria")
    op.drop_table("acceptance_criteria")
    op.drop_index(op.f("ix_tasks_epic_id"), table_name="tasks")
    op.drop_table("tasks")
    op.drop_table("epics")
    op.drop_index(op.f("ix_domain_events_aggregate_id"), table_name="domain_events")
    op.drop_index("ix_domain_event_timeline", table_name="domain_events")
    op.drop_table("domain_events")
    op.drop_table("actors")
    # ### end Alembic commands ###
